apiVersion: v1
kind: Service
metadata:
  name: karmada-scheduler
  namespace: karmada-system
spec:
  selector:
    app: karmada-scheduler
  ports:
  - port: 10351
    protocol: TCP
    targetPort: 10351