kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  namespace: monitor
spec:
  capacity:
    storage: 10Gi   #设置空间大小
  volumeMode: Filesystem
  accessModes: ["ReadWriteOnce"]
  local:
    path: /var/lib/grafana-data
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ecs-karmada-control-plane
